"""empty message

Revision ID: 851a000adef2
Revises: 1acc727cf4a6
Create Date: 2019-03-23 22:00:49.978542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851a000adef2'
down_revision = '1acc727cf4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_url'), 'jobs', ['url'], unique=True)
    op.drop_index('jobs_url_uindex', table_name='jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('jobs_url_uindex', 'jobs', ['url'], unique=True)
    op.drop_index(op.f('ix_jobs_url'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    # ### end Alembic commands ###
