"""empty message

Revision ID: 8d646ef5d1e2
Revises: 8bc23ac417f6
Create Date: 2019-03-24 12:03:19.703734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d646ef5d1e2'
down_revision = '8bc23ac417f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_match', 'matchs', ['user_id', 'job_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_match', 'matchs', type_='unique')
    # ### end Alembic commands ###
